name: TalkHint
options:
  bundleIdPrefix: app.talkhint
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  createIntermediateGroups: true
settings:
  base:
    DEVELOPMENT_TEAM: 6G9ZS426J3
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"
packages:
  TwilioVoice:
    url: https://github.com/twilio/twilio-voice-ios
    from: "6.11.0"
targets:
  TalkHint:
    type: application
    platform: iOS
    sources:
      - path: TalkHint
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.talkhint
        PRODUCT_NAME: TalkHint
        INFOPLIST_FILE: TalkHint/Info.plist
        CODE_SIGN_ENTITLEMENTS: TalkHint/TalkHint.entitlements
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_BITCODE: NO
    dependencies:
      - package: TwilioVoice
        product: TwilioVoice
  TalkHintTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TalkHintTests
    dependencies:
      - target: TalkHint
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.talkhint.tests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TalkHint.app/TalkHint"
        BUNDLE_LOADER: "$(TEST_HOST)"
schemes:
  TalkHint:
    build:
      targets:
        TalkHint: all
        TalkHintTests: [test]
    test:
      targets:
        - TalkHintTests
