// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tutor-v4/AttachInChat.tsx": () => import("../components/mockups/tutor-v4/AttachInChat.tsx"),
  "./components/mockups/tutor-v4/AttachMenu.tsx": () => import("../components/mockups/tutor-v4/AttachMenu.tsx"),
  "./components/mockups/tutor-v4/Dialog.tsx": () => import("../components/mockups/tutor-v4/Dialog.tsx"),
  "./components/mockups/tutor-v4/ErrorRetry.tsx": () => import("../components/mockups/tutor-v4/ErrorRetry.tsx"),
  "./components/mockups/tutor-v4/ExitConfirm.tsx": () => import("../components/mockups/tutor-v4/ExitConfirm.tsx"),
  "./components/mockups/tutor-v4/FramingHalf.tsx": () => import("../components/mockups/tutor-v4/FramingHalf.tsx"),
  "./components/mockups/tutor-v4/HintLoading.tsx": () => import("../components/mockups/tutor-v4/HintLoading.tsx"),
  "./components/mockups/tutor-v4/HintReady.tsx": () => import("../components/mockups/tutor-v4/HintReady.tsx"),
  "./components/mockups/tutor-v4/LongConversation.tsx": () => import("../components/mockups/tutor-v4/LongConversation.tsx"),
  "./components/mockups/tutor-v4/MemoryConfirmed.tsx": () => import("../components/mockups/tutor-v4/MemoryConfirmed.tsx"),
  "./components/mockups/tutor-v4/MemoryPending.tsx": () => import("../components/mockups/tutor-v4/MemoryPending.tsx"),
  "./components/mockups/tutor-v4/MemoryReview.tsx": () => import("../components/mockups/tutor-v4/MemoryReview.tsx"),
  "./components/mockups/tutor-v4/Ready.tsx": () => import("../components/mockups/tutor-v4/Ready.tsx"),
  "./components/mockups/tutor-v4/ReadyEn.tsx": () => import("../components/mockups/tutor-v4/ReadyEn.tsx"),
  "./components/mockups/tutor-v4/Recording.tsx": () => import("../components/mockups/tutor-v4/Recording.tsx"),
  "./components/mockups/tutor-v4/Speaking.tsx": () => import("../components/mockups/tutor-v4/Speaking.tsx"),
  "./components/mockups/tutor-v4/TextInput.tsx": () => import("../components/mockups/tutor-v4/TextInput.tsx"),
  "./components/mockups/tutor-v4/Thinking.tsx": () => import("../components/mockups/tutor-v4/Thinking.tsx"),
  "./components/mockups/tutor-v4/TranslateLoading.tsx": () => import("../components/mockups/tutor-v4/TranslateLoading.tsx"),
  "./components/mockups/tutor-v4/TranslateOpen.tsx": () => import("../components/mockups/tutor-v4/TranslateOpen.tsx"),
  "./components/mockups/tutor-v4/UserCommitted.tsx": () => import("../components/mockups/tutor-v4/UserCommitted.tsx")
};
